export const BUCKETS_ERROR = "BUCKETS_ERROR";
export const BUCKETS_LOADING = "BUCKETS_LOADING";
export const BUCKETS_SUCCESS = "BUCKETS_SUCCESS";
export const BUCKET_DETAIL_ERROR = "BUCKET_DETAIL_ERROR";
export const BUCKET_DETAIL_LOADING = "BUCKET_DETAIL_LOADING";
export const BUCKET_DETAIL_SUCCESS = "BUCKET_DETAIL_SUCCESS";
