export const TASKS_ERROR = "TASKS_ERROR";
export const TASKS_LOADING = "TASKS_LOADING";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const CREATE_TASKS_ERROR = "CREATE_TASKS_ERROR";
export const CREATE_TASKS_LOADING = "CREATE_TASKS_LOADING";
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS";
