export const TASKS_ERROR = "TASKS_ERROR";
export const TASKS_LOADING = "TASKS_LOADING";
export const TASKS_SUCCESS = "TASKS_SUCCESS";

export const CREATE_TASKS_ERROR = "CREATE_TASKS_ERROR";
export const CREATE_TASKS_LOADING = "CREATE_TASKS_LOADING";
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS";

export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";
export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";